spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:petdb
    username: sa
    password:
  sql.init.mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true