spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:petdb
    username: sa
    password:
  sql.init.mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

logging:
  level:
    com:
      rozsa:
        events:
          collector: DEBUG

rozsa:
  events-collector:
    submit-endpoint: 'http://localhost:8090/collect'
    event-id-key: 'event_id'
    flows:
      flowAStar:
        submit-endpoint: 'http://localhost:9999/collect/flow-a'
        event-id-key: 'flow_a_key'